- .travis.yml
- config.m4
- src/php_spx.h
- src/spx_profiler.c
- src/spx_reporter_fp.c
- src/spx_resource_stats-macos.c
- src/spx_resource_stats.c
- src/spx_stdio.c
- src/spx_utils.c
- src/spx_utils.h
I saw that issue #7 was marked as postponed, but since I wanted this for my own purposes I decided to have a go.
This implements the minimum possible changes to build & run on OSX/macos. Some notable points:
- Fine-grained timing isn't available as cheaply/simply as on linux, so I've used coarser clocks/timing info. I doubt this is too much of an issue, as everything in the linux impl is converted down to µsec anyway.
- No I/O stats. I've searched high and low and can't find any I/O stats per-process in osx without using dtrace, which feels excessive: it would be a complicated integration, requires root, and requires a [one-off SIP reconfiguration](https://8thlight.com/blog/colin-jones/2017/02/02/dtrace-gotchas-on-osx.html).
This was built & tested on 10.11 (El Capitan), which is the same …
> Basic Mac OSX support

- .travis.yml
- README.md
- src/spx_resource_stats-macos.c
As discussed in #30, uses `clock_gettime` for nanosecond resolution timing on macos >= 10.12 (Sierra), keeping the coarser microsecond timings on older versions.
> Nanosecond timers for macos, where possible

- src/php_spx.c
- src/spx_profiler.c
- src/spx_reporter_full.h
- Profiler object does not have anymore the responsability to destroy its passed (at creation time) reporter
- Signal handler does not call `exit()` anymore (fix #42)
> Fix ownership issue & fix #42

- assets/web-ui/css/main.css
- assets/web-ui/js/utils.js
- assets/web-ui/js/widget.js
- assets/web-ui/report.html
As discussed in #43, an initial implementation of user-definable categories in the web UI.
It won't win any awards for UX or front-end code quality, but it's reasonably functional! I tried to keep code changes to a minimum but of course there is some fiddly UI state management required.
This change only adds support for colouring categories in the overview/timeline widgets – I haven't done the flat profile table yet.
You can add & remove categories; edit their labels, regex patterns & colours; and change the precedence order. Click outside of the panel (or press esc) to dismiss.
Here's a [gif](https://d3vv6lp55qjaqc.cloudfront.net/items/1M1b1q3k2i2C0C0X3U2P/Screen%20Recording%202018-04-06%20at%2002.14%20pm.gif) showing it in action.
> User-definable Categories in web UI

- README.md
- src/php_spx.c
- src/spx_config.c
- src/spx_config.h
- src/spx_fmt.c
- src/spx_fmt.h
- src/spx_reporter_fp.c
- src/spx_reporter_fp.h
Printed values are now colored according to their weights (i.e.
distance from max value) when STDOUT is a TTY.
Resolve #52
> CLI: Add color scheme to flat profile

- src/spx_resource_stats-macos.c
On macOS 10.11 and lower, spx_resource_stats_*_coarse() local functions
defined & used in src/spx_resource_stats-macos.c were not properly
declared on top of file, resulting in a compilation error (missing
declaration) on these platforms.
Fixes #78
> macOS 10.11-: add forward function declarations

- Makefile.frag
As packaging shows https://travis-ci.org/alpinelinux/aports/builds/449814270
Assets install should allow install into configurable directory (php extensions use `INSTALL_ROOT` for `make install`)
```
Installing SPX web UI to: /usr/share/misc/php-spx/assets/web-ui
mkdir: can't create directory '/usr/share/misc/php-spx/': Permission denied
make: *** [Makefile:199: install-spx-ui-assets] Error 1
make: *** Waiting for unfinished jobs....
Installing shared extensions:     /home/travis/build/alpinelinux/aports/testing/php7-spx/pkg/php7-spx/usr/lib/php7/modules/
```
> Make spx_ui_assets_dir respect INSTALL_ROOT

- config.m4
- src/spx_profiler_sampler.c
The current implementation of sampling profiler decorator, based on
XHProf one, has still a lower (compared to tracing profiler) but
significant overhead due to the fact that it calls `clock_gettime()`
on each function call/start.
This patch make it use a background thread.
It may also fix #91 as `last_sample_time_ns` was not properly
initialized in previous implementation.
> Sampling profiler: improve performance

- README.md
Fatal error occurs without SSH keys in your account:
```
git clone git@github.com:NoiseByNorthwest/php-spx.git
Cloning into 'php-spx'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
> Change repository to https-version in "Install the extension" section

- README.md
- src/php_spx.c
Allow to whitelist all IP addresses in `spx.http_ip_whitelist` using `*`. Fix #95.
Having something like
```
extension=spx.so
spx.http_enabled=1
spx.http_key="dev"
spx.http_ip_whitelist="*"
```
works on docker with ease
> Allow to whitelist all IP addresses in `spx.http_ip_whitelist` (#95)

- README.md
- src/php_spx.c
- src/spx_config.c
- src/spx_config.h
- src/spx_php.c
- tests/spx_auto_start_001.phpt
- tests/spx_auto_start_002.phpt
- tests/spx_auto_start_003.phpt
- tests/spx_auto_start_004.phpt
This patch adds the support for self-code instrumentation in order
to let the user to trigger the profiling for a specific part of
the script at runtime.
The 2 following userland functions are added:
- `spx_profiler_start(): void`
- `spx_profiler_stop(): void`
This feature requires the PHP script to be configured with:
- SPX_ENABLED=1
- SPX_AUTO_START=0 -> this is a newly added parameter (with `1` as
default value) for the purpose of this feature.
See the updated documentation for more details.
Resolves #107
> Allow to define the profiled spans at runtime

- assets/web-ui/report.html
Using native js in setProgress improves time of page rendering.
It can be noticeable on huge profiles in apps like Magento 2
On demo link it gives about 200ms
https://noisebynorthwest.github.io/php-spx/demo/report.html?key=spx-full-20191229_175636-06d2fe5ee423-3795-233665123
> Replace jquery calls with native methods for setProgress

- src/spx_profiler_tracer.c
When depth limit (i.e. `SPX_DEPTH`) is used the produced report
is corrupted, with more call starts recorded than call ends.
The "above limit" check was made at the wrong place, this patch
fixes it.
Fixes #118
> Fix broken report when profiling with depth limit

- src/spx_profiler_sampler.c
This patch fixes an unsigned integer overflow issue within sampling
profiler module which causes an OBOE in the loop calling the ending
probes of the previous sample stack. Thus, the ending probe being
called too many times eventually raises a "Cannot rewind below 0
depth" error.
Fixes #116
> Fix fatal error when sampling is enabled

- README.md
- assets/web-ui/js/math.js
- assets/web-ui/js/widget.js
This patch adds the possibility, within the report analysis screen,
to highlight a function by clicking on one of its spans within the
timeline or Flamegraph widgets or on its name within the flat
profile widget.
> Report analysis screen: add function highlighting

- assets/web-ui/js/widget.js
This patch makes the selected call's information selectable within
the timeline widget.
Fixes #124
> Analysis screen/timeline: call info selectable

- assets/web-ui/js/profileData.js
- assets/web-ui/js/utils.js
This patch makes the report analysis screen not dependant anymore
of big arrays. It now uses chunked arrays (i.e. multi-buffers backed
arrays) in order to circumvent the ArrayBuffer size limit (2^31 - 1).
References #123
> Report analysis: use chunked arrays

- src/spx_resource_stats-linux.c
Fixes the following compilation error (see #121):
src/spx_resource_stats-linux.c: In function 'spx_resource_stats_own_rss':
src/spx_resource_stats-linux.c:118:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < sizeof(context.lg_buf); i++) {
^
src/spx_resource_stats-linux.c:118:5: note: use option -std=c99 or -std=gnu99 to compile your code
> Make compilation succeed with gnu90

- config.m4
gnu90 appears to be the best standard to enforce right now, regarding both its cost (in terms of lack of feature) and its support being widespread.
Forcing gnu90 as explicit standard to enforce will avoid issues like #121 & #146 in the future.
> Force -std=gnu90 compilation flag

- README.md
The aim of this pull request is to add an example to the readme how to trigger SPX profiling using curl from the command line.
> Added curl profiling to readme

- .travis.yml
This should resolve the CI request given in #156
5.6 and 7.0 have been excluded from the matrix as it looks like they don't have a copy of PHP compiled for ARM for anything less than 7.1
I've also PHP 8 support back into the matrix as it looks like Travis has started supporting it since the config was last touched.
> [CI] ARM + PHP 8 CI support 

- src/php_spx.c
The `spx_profiler_start` and `spx_profiler_stop` functions require `auto_start` to be disabled.
The wording of the log notice tells you the inverse.
> Fix autostart wording on usage of spx_profiler

- README.md
It's probably better to build php-spx using the latest released version.
> Build specific version of php-spx instead of latest commit on master

- .github/workflows/main.yml
- CHANGELOG.md
- src/php_spx.h
Hi @NoiseByNorthwest 
I forgot to enable Release action in PR #190, so this PR will fix this. Also I've bumped SPX version from 0.4.12 to v0.4.13
You can see how it works in my fork:
[Release](https://github.com/AlexNDRmac/php-spx/releases/tag/v0.4.13-test2)
[Action run](https://github.com/AlexNDRmac/php-spx/actions/runs/3145724831/jobs/5113396847)
After merging this PR - you'll be able to create Release with pushing tag or just manually creating Release as usually. Action will build all the artifacts, creates release notes from Changelog.md details, attach all the build artifacts (compiled extension with web-ui for each PHP version) to the release assets.
> Enable Release action

- config.m4
fix compilation with debug symbols https://github.com/NoiseByNorthwest/php-spx/issues/208
> Add --enable-spx-dev to compile with debug symbols

- .github/workflows/build-debian-ext/Dockerfile
- .github/workflows/build-debian-ext/action.yml
- .github/workflows/build-linux-mac-ext/action.yml
- .github/workflows/main.yml
- CHANGELOG.md
Hi @NoiseByNorthwest
I've reworked github actions to add Debian builds.
Now, github workflow split on two separate actions. It allows us to compile extension for ubuntu and macos, and build extension for Debian.
Debian users as an Ubuntu users - can download build extension and use it OOB (without compilation)
Also, I've updated Changelog, because it obsolete.
> Builds for debian

- assets/web-ui/index.html
- assets/web-ui/js/fmt.js
- assets/web-ui/js/profileData.js
- assets/web-ui/js/utils.js
- assets/web-ui/js/widget.js
- assets/web-ui/report.html
when the page url path does not finish with / and parent directory does not load php a script, ESM imports fail because resolution algorithm differ from the one used for script src
fixes #233
> fix esm imports

- README.md
- config.m4
- src/php_spx.h
- src/spx_utils.c
> Allow ZTS PHP

- assets/web-ui/js/widget.js
> Keep scroll position in flatprofile view on repaint

- assets/web-ui/css/main.css
Related issues: #225 
This pull request extracts all CSS colors out into CSS variables and adds support for light mode.
Here are some screenshots (I'm not a designer, so if the colors are off I'm open for suggestions):
Extracting colors into variables makes it able to be reused throughout the code and just having a set palette to reference. It makes it more consistent and easier to change.
In this case the light mode just sets different values for the variable and the rest of the rendering stays as is.
One thing to note here is that the SVG for the color scale is now also theme based. This is achieved by using `currentColor` in the SVG code which allows it to be styled with CSS.
In a "modern" browser everything should work. IE is definitely not supported but here is the full list of …
> Adding light theme based on operating system settings
