NoiseByNorthwest/php-spx

- src/php_spx.c
- src/spx_reporter_fp.c
> Alpine Linux compatibility patches

- src/spx_reporter_full.c
- tests/spx_006.phpt
> Fix macos build

- src/spx_php.c
- tests/spx_gc_traced.phpt
- tests/spx_gc_traced_7_0.phpt
- tests/spx_gc_traced_7_2.phpt
> Add GC tracing

- assets/web-ui/js/widget.js
> web ui: fix flat profile metric name

- src/php_spx.c
- src/spx_php.c
- src/spx_php.h
- tests/spx_auth_ko_ip.phpt
- tests/spx_auth_ko_key.phpt
- tests/spx_auth_ok.phpt
- tests/spx_log_hidden.phpt
- tests/spx_log_printed.phpt
- handle notice logs
- do not log when log_errors is off
- add test cases
Fixes #24
> Log management cleanup

- README.md
- src/php_spx.c
- src/spx_php.c
- src/spx_php.h
- tests/spx_auth_ko_ip.phpt
- tests/spx_auth_ko_key.phpt
- tests/spx_auth_ok.phpt
- tests/spx_log_hidden.phpt
- tests/spx_ui_301.phpt
- tests/spx_ui_404.phpt
Additionaly:
- fix 404 responses
- add 301 redirection from `{prefix}` to `{prefix}/`
Fixes #27
> Refactor HTTP responses management.

- README.md
- assets/web-ui/js/math.js
- assets/web-ui/js/widget.js
> Web UI: make time range rect resizeable

- src/php_spx.c
- src/spx_php.c
- src/spx_php.h
> Remove output deactivation related code

- README.md
- assets/web-ui/css/main.css
- assets/web-ui/index.html
- src/php_spx.c
- src/spx_metric.c
- src/spx_metric.h
- src/spx_php.c
- src/spx_php.h
- src/spx_reporter_fp.c
- src/spx_reporter_trace.c
- tests/spx_auth_ok.phpt
Add the following metrics:
- Zend Engine included file count
- Zend Engine class count
- Zend Engine function count
> Add 3 Zend Engine related metrics

- README.md
- assets/web-ui/css/main.css
- assets/web-ui/index.html
- assets/web-ui/js/fmt.js
- assets/web-ui/js/math.js
- assets/web-ui/js/profileData.js
- assets/web-ui/js/widget.js
- assets/web-ui/report.html
- Control panel: output command line prefix according to current setup
- Analysis screen: improve loading performance a bit
- Analysis screen: improve loading progress dialog
- Analysis screen: add cumulative cost computation and fix flat profile
percentage columns #41
- Analysis screen: display bars in flat profile percentage columns #40
> Web UI: various improvements

- README.md
- assets/web-ui/js/profileData.js
- assets/web-ui/js/utils.js
- assets/web-ui/js/widget.js
- assets/web-ui/report.html
- refactor some recent changes
- add "category" color scheme handling for Flamegraph & flat profile
- fix broken flat profile when selected timerange is smaller than the
smallest call in the timeline view
- fix broken callgraph profile when selected timerange is smaller than the
smallest call in the timeline view
- improve documentation around web UI requirements (fixes #54)
> Web UI: several fixes & improvement

- src/spx_fmt.c
- src/spx_php.c
- src/spx_profiler.c
- src/spx_reporter_fp.c
- src/spx_reporter_full.c
- src/spx_utils.c
- src/spx_utils.h
- add fatal error handling routine
- remove some memory leak paths
> Profiler: cleaning

- src/php_spx.c
- src/spx_php.c
- src/spx_php.h
> Clean (and fix for ZTS) global hooks use

- src/spx_php.c
> Fix Zend hooks wrapping

- assets/web-ui/js/layoutSplitter.js
- assets/web-ui/js/svg.js
- assets/web-ui/js/widget.js
- assets/web-ui/report.html
This patch adds:
- 2 layout splitters to give some control over the size of the
timeline, flat profile & Flamegraph widgets.
It also fixes:
- resizing issues with appearing/disappearing scrollbar.
- repaint events unlimited accumulation.
It also slightly improves performance via:
- the use of document fragments to efficiently add many child nodes
to a DOM element.
- the exclusion of unvisible function calls accordingly to their
y-axis position while rendering timeline widget.
> Report UI improvements

- assets/web-ui/report.html
> Report UI: add throughput to loading progress

- README.md
> Document the PHP-FPM & procfs permission issue

- src/php_spx.c
> Make compilation succeed with gnu90

- assets/web-ui/js/widget.js
> Report analysis/timeline: fix selected call info

- README.md
- src/php_spx.c
- src/spx_config.c
- src/spx_config.h
- src/spx_php.c
- src/spx_php.h
- tests/spx_ini_params_no_effect_in_cli.phpt
- tests/spx_ini_params_not_overridden.phpt
- tests/spx_ini_params_overridden.phpt
- tests/spx_ini_params_profiling_disabled.phpt
- tests/spx_ini_params_profiling_enabled.phpt
> Expose some profiling parameters at INI level

- README.md
The objective of this PR is to update the readme for [Partial access to SPX control panel if index.php does not exist](https://github.com/NoiseByNorthwest/php-spx/issues/145)
> Updated readme requirements for the control panel to load

- README.md
- src/php_spx.c
- src/spx_reporter_full.c
- src/spx_reporter_full.h
- tests/spx_auto_start_005.phpt
- tests/spx_auto_start_006.phpt
> Make spx_profiler_stop() return the report key

- README.md
- src/spx_resource_stats-freebsd.c
- src/spx_resource_stats.c
> Basic FreeBSD support

- README.md
> Add "Buy Me a Coffee" link

- README.md
- assets/web-ui/index.html
- src/php_spx.c
- src/spx_config.c
- tests/spx_auth_ip_trusted_proxy_ko.phpt
- tests/spx_auth_ipv6_trusted_proxy_ko.phpt
- tests/spx_auto_start_006.phpt
- tests/spx_auto_start_007.phpt
> Add AUTO_START parameter support for non-CLI

- .gitignore
- .travis.yml
- README.md
- src/php_spx.h
- src/spx_php.c
- tests/spx_gc_traced_7_3+.phpt
- tests/spx_gc_traced_8_0+.phpt
- tests/spx_userland_stats_5_6_7_2.phpt
- tests/spx_userland_stats_7_3+.phpt
- tests/spx_userland_stats_7_3.phpt
- tests/spx_userland_stats_7_4.phpt
- tests/spx_userland_stats_8_0+.phpt
> Add PHP 8.1 support

- src/php_spx.c
> Fix null pointer dereference

- README.md
Describe how to solve a blank web GUI page by adjusting a PHP parameter.
> Add note about blank GUI page

- src/php_spx.h
https://github.com/php/php-src/blob/327c95237c96c517bd72671404686b9f5c2af8bb/Zend/zend_modules.h#L34
It's working in my docker image https://github.com/8ctopus/apache-php-fpm-alpine/releases/new
> Add support for php 8.2.0 RC2

- README.md
- assets/web-ui/index.html
- src/php_spx.c
- src/spx_reporter_full.c
- src/spx_reporter_full.h
- src/spx_utils.c
- tests/spx_custom_metadata.phpt
Resolves #173. This need is also mentionned in #197.
> Custom metadata support

- README.md
> Add stubs for intelephense to readme

- src/spx_php.c
- src/spx_str_builder.c
> Increase command line str builder buffer size

- config.m4
> Add zlib-dev search path

- assets/web-ui/index.html
- assets/web-ui/report.html
Fix local script usage (introduced in https://github.com/NoiseByNorthwest/php-spx/pull/248 which I blindly copied from https://github.com/NoiseByNorthwest/php-spx/issues/217#issuecomment-2241207488) to be consistent with other scripts
> Fix jquery scripts

- src/php_spx.c
- tests/spx_ui_uri_confinement.phpt
> Web UI: fix unconfined file access via SPX_UI_URI

- README.md
- src/php_spx.c
- src/spx_utils.c
- src/spx_utils.h
- tests/spx_auth_ip_subnet_ko_1.phpt
- tests/spx_auth_ip_subnet_ko_2.phpt
- tests/spx_auth_ip_subnet_ko_3.phpt
- tests/spx_auth_ip_subnet_ok.phpt
> Add subnet mask support for IP matching

- src/spx_php.c
> Make Zend MM custom handler state thread-local

- src/php_spx.c
- src/php_spx.h
- src/spx_fmt.c
- src/spx_hmap.h
- src/spx_php.c
- src/spx_php.h
- src/spx_profiler_tracer.c
- src/spx_reporter_fp.c
- src/spx_reporter_full.c
- src/spx_reporter_trace.c
- src/spx_resource_stats-win32.c
- src/spx_stdio-unix.c
- src/spx_stdio-win32.c
- src/spx_stdio.c
- src/spx_stdio.h
- src/spx_utils.c
- src/spx_utils.h
This patch is not a complete support of windows. Its goal is to port to master branch right now the current changes made to src/ to support windows.
See here: https://github.com/NoiseByNorthwest/php-spx/pull/263
> Add some changes required for win support
